### ISSUE TITLE
Whats the deal with SteamTools?

### ISSUE THREAD

**Issue by Alkaris** [asherkin/SteamTools#2]
Can't use the scripts to compile this for some reason, and I `steamtools.ext.so`

when I run the `configure.py` script all I get is this junk;

```
$ python ./configure.py 
Checking c compiler (vendor test gcc)... ['gcc', 'test.c', '-o', 'test']
found gcc version 7.3
Checking cxx compiler (vendor test gcc)... ['g++', '-fno-exceptions', '-fno-rtti', 'test.cxx', '-o', 'testp']
found gcc version 7.3
Traceback (most recent call last):
  File "./configure.py", line 10, in <module>
    run.Configure(sys.path[0])
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 113, in Configure
    self.LoadFile(os.path.join(self.sourceFolder, 'AMBuildScript'))
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 137, in LoadFile
    _execfile(path, globals)
  File "/usr/local/lib/python2.7/dist-packages/ambuild/runner.py", line 12, in _execfile
    exec(compile(open(file).read(), file, 'exec'), globals)
  File "/home/******/SteamTools/AMBuildScript", line 412, in <module>
    sm = SM()
  File "/home/******/SteamTools/AMBuildScript", line 111, in __init__
    raise Exception('Could not find a valid path for {0}'.format(i))
Exception: Could not find a valid path for SOURCEMOD16
```

what is any of this suppose to mean, what reference for `SOURCEMOD16` is it suppose to look for when this script is ran?

**Comment by asherkin** [comment]
You are missing the dependencies, you need to checkout a copy of MM:S' `1.9-dev` branch to a directory called `mmsource-1.9` next to your steamtools checkout, a copy of SM's `1.7-dev` branch (don't forget to do a recursive clone) to a directory called `sourcemod-1.7`, and a copy of hl2sdk's `tf2` branch to a directory called `hl2sdk-tf2`.

```
git clone --branch=tf2 https://github.com/alliedmodders/hl2sdk hl2sdk-tf2
git clone --branch=1.9-dev https://github.com/alliedmodders/metamod-source mmsource-1.9
git clone --branch=1.7-dev --recursive https://github.com/alliedmodders/sourcemod sourcemod-1.7
```
